# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-01 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=50)),
                ('courseCatagory', models.CharField(max_length=50)),
                ('startDate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examName', models.CharField(max_length=100)),
                ('examComplexity', models.CharField(max_length=20)),
                ('examMarks', models.IntegerField()),
                ('examDuration', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineEducation.Course')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('optionA', models.CharField(max_length=100)),
                ('optionB', models.CharField(max_length=100)),
                ('optionC', models.CharField(max_length=100)),
                ('optionD', models.CharField(max_length=100)),
                ('correctAnswer', models.CharField(max_length=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineEducation.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=50)),
                ('studentAddress', models.CharField(max_length=50)),
                ('studentInstitution', models.CharField(max_length=50)),
                ('studentClass', models.CharField(max_length=10)),
                ('studentContact', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=50)),
                ('teacherAddress', models.CharField(max_length=50)),
                ('teacherInstitution', models.CharField(max_length=50)),
                ('teacherDesignation', models.CharField(max_length=50)),
                ('teacherContact', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='courseStudent',
            field=models.ManyToManyField(to='onlineEducation.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='courseeacher',
            field=models.ManyToManyField(to='onlineEducation.Teacher'),
        ),
    ]
