# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-01 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineEducation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseeacher',
            new_name='courseTeacher',
        ),
    ]
